### ISSUE TITLE
Send Order shipping tracking number to zendesk

### ISSUE THREAD

**Issue by manohar-prabhu** [wagento/zendesk#28]
We have integrated wagento/zendesk 220.0.1 magento2 module in our system. We would like to send "shipping tracking number" to zendesk. As per current module, it does not allow to send it to zendesk.

**Comment by mrprabhu** [comment]
@wagento when we can expect further information on this issue?

**Comment by jhon-MT** [comment]
Hello @mrprabhu,

To understand correctly, are you looking to pull the tracking information into Zendesk portal based on the order number?  This could indeed be a new addition to our extension.

At the moment we are in the planning stage of a new release compatible with Magento 2.3 so we could also add this feature into the backlog but at the moment we do not have an ETA of when this will be made available.

Thank you for your suggestions!

**Comment by TonyRutherford1** [comment]
@jhon-MT Yes, we are looking at pulling in the tracking number from Magento to Zendesk, so we can see customer information, order number and tracking number of order

**Comment by mrprabhu** [comment]
@jhon-MT we will update Wagento module to add tracking number in it so that it will pass to Zendesk on sync of customer orders.
Kindly let us know which array parameter should we use to transfer `tracking number` to Zendesk,
Please check the screenshot.
![image](https://user-images.githubusercontent.com/35934158/52837223-dccbe380-3113-11e9-8fa3-d1103be6413c.png)

In `$orderInfo` array module is using `increment_id` parameter for `Order increment id` or `shipping_amount` parameter for `order shipping amount` in same way please provide us name of a parameter for `tracking number` so that we can use it and we can transfer data to Zendesk.

Thanks.

**Comment by TonyRutherford1** [comment]
@jhon-MT Any feedback re above?

**Comment by JDavidVR** [comment]
Hi @mrprabhu thanks for help improving **Zendesk module for Magento**

Tracking number can be added as an addition item in array under "shipping_method" see here: https://github.com/wagento/zendesk/blob/master/Model/Data/CustomerOrder.php#L305

So right now like an order can have many tracking number sent is as an array:
```
'shipping_method' => $shippingMethod,
'tracking_number' => ["TCODE0001", "TCODE0002", "TCODE0003"],
'items' => []
```
So that information will be displayed as it look for **Tags** on **Magento app for Zendesk**
https://136787.apps.zdusercontent.com/136787/assets/1510938156-b99a16dc75334af68bb0ff5d2dcff7e3/screenshot-1.png


Regards!

**Comment by mrprabhu** [comment]
Hi @JDavidVR thanks for the help.
We have tried sending a test tracking number to zendesk as suggested by you, but it is not working.
![image](https://user-images.githubusercontent.com/35934158/54271360-5cc85a80-45a7-11e9-9be2-ffe1c68bd64a.png)


![image](https://user-images.githubusercontent.com/35934158/54271235-24c11780-45a7-11e9-98cf-38fa19d15c66.png)

Can you please update your solution?

**Comment by JDavidVR** [comment]
Hi @mrprabhu 

I am so sorry for the misunderstanding, my previous comment was a proposal, that you can create a pull request for the repo, with the tracking logic.

Once we make sure that api is working correctly we will update "Magento 2 App for Zendesk" widget to show traking information.

Regards!

**Comment by mibbinyatnam** [comment]
@JDavidVR 

Any updates on the issue? When we can expect further information on this issue?

**Comment by manohar-prabhu** [comment]
@simonmaass @jhon-wagento I have modified zendesk module and added respective code to it but while pushing code to zendesk repo it doesn't allow me to push.

![image](https://user-images.githubusercontent.com/35934158/59487100-3e6d4600-8e99-11e9-9baa-af955131184c.png)

I have added ssh key to my git repo and also tried with Switching remote URLs from SSH to HTTPS but no luck.

**Comment by ArchanaMohan1** [comment]
@JDavidVR  :Can we please have an update on this?

**Comment by ArchanaMohan1** [comment]
@JDavidVR :Can we please have an update on this?

**Comment by ArchanaMohan1** [comment]
@simonmaass @jhon-wagento @JDavidVR --- :Can we please have an update on this?

**Comment by ArchanaMohan1** [comment]
@simonmaass @jhon-wagento @JDavidVR --- :Can we please have an update on this?

**Comment by JDavidVR** [comment]
Hi @manohar-prabhu 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
